### ISSUE TITLE
Site width issue

### ISSUE THREAD

**Issue by Hi-Ray** [afranche/bebou#1]
Great app! 

currently the site width has an issue on my screen I have tested this on my laptop and desktop and come across the same issue which is where the width is limited to 60% of the screen.

![Image](https://github.com/user-attachments/assets/e772ed47-89aa-40a0-985d-9cfbb0711eae)

Image attached to display the issue I am having.

I would love to contribute but I am waiting on the contribution guide.

Also is there any plans for this to be put on other devices or will this remain a web app.

Thanks for the great work!

**Comment by afranche** [comment]
Hi Ray, thanks a lot for the kind words ! ❤ 

I just noticed the issue came from the leftover styling left by Vite's React template. I cleaned it in [caf7ca9](https://github.com/afranche/bebou/commit/caf7ca99c8c40d2248d9356de625e95d91f50346) so it should work now, would you mind checking it again ?

Cheers!

**Comment by Hi-Ray** [comment]
![Image](https://github.com/user-attachments/assets/9902d352-1d7b-4f29-8e67-510553afc8fa)

Sadly still the same issue on my laptop.

**Comment by Hi-Ray** [comment]
never mind it was a caching issue it works!

Thank you <3
